spring.application.name=lobby
server.port=8081
spring.data.mongodb.uri=mongodb+srv://mateosebastianforerofuentes:QXUib1uFI1aBvw05@cluster0.xyzrk.mongodb.net/db_pigball?retryWrites=true&w=majority&appName=Cluster0

