spring.application.name=lobby
server.port=8081
spring.data.mongodb.uri=mongodb+srv://mateosebastianforerofuentes:QXUib1uFI1aBvw05@cluster0.xyzrk.mongodb.net/db_pigball?retryWrites=true&w=majority&appName=Cluster0
# logging.level.org.springframework.messaging=DEBUG
# logging.level.org.springframework.web.socket=DEBUG
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server.ssl.key-store-type=PKCS12
# The path to the keystore containing the certificate
server.ssl.key-store=classpath:ecikeystore.p12
# The password used to generate the certificate
server.ssl.key-store-password=123456
# The alias mapped to the certificate
server.ssl.key-alias=ecikeypair
server.ssl.enabled=true
